#!/usr/bin/with-contenv bash
USER_POLICY="/config/.config/mdm.xml"
LOCAL_POLICY="/var/lib/cloudflare-warp/mdm.xml"

[[ -d /var/lib/cloudflare-warp ]] || mkdir -p /var/lib/cloudflare-warp

if [[ -f $USER_POLICY && ! -f $LOCAL_POLICY ]]; then
	echo "Linking policy file"
	ln -sf $USER_POLICY $LOCAL_POLICY
fi
