#!/usr/bin/with-contenv bash

# Install Telegram PPA
add-apt-repository ppa:atareao/telegram

# Install Signal Repo key
cd /tmp
wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
cat signal-desktop-keyring.gpg | tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

# Add Signal repo
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' |\
  tee /etc/apt/sources.list.d/signal-xenial.list

# Update and install packages
apt update
apt install telegram signal-desktop chromium-browser