#!/usr/bin/with-contenv bash

# Added to use cloudflare warp
#export HTTPS_PROXY=http://127.0.0.1:40000

SESSID=$(pwgen 10 1)
export HTTP_PROXY="customer-${OXYLABS_USER}-st-${OXYLABS_EXIT}-sessid-${SESSID}-sesstime-30:${OXYLABS_PASS}@pr.oxylabs.io:7777"
export http_proxy="customer-${OXYLABS_USER}-st-${OXYLABS_EXIT}-sessid-${SESSID}-sesstime-30:${OXYLABS_PASS}@pr.oxylabs.io:7777"
export HTTPS_PROXY="customer-${OXYLABS_USER}-st-${OXYLABS_EXIT}-sessid-${SESSID}-sesstime-30:${OXYLABS_PASS}@pr.oxylabs.io:7777"
export https_proxy="customer-${OXYLABS_USER}-st-${OXYLABS_EXIT}-sessid-${SESSID}-sesstime-30:${OXYLABS_PASS}@pr.oxylabs.io:7777"

cd $HOME
exec s6-setuidgid abc \
  /bin/bash /defaults/startwm.sh
