#!/usr/bin/with-contenv bash
SQUID_CONF=/config/.config/squid.conf

EXIT_STR=""
[[ -z "$OXYLABS_EXIT" ]] || EXIT_STR="st-${OXYLABS_EXIT}-"

SESSID=$(pwgen 10 1)

cat >${SQUID_CONF} <<EOF
http_port 4000
pid_filename /tmp/squid.pid
pinger_enable off
cache_peer pr.oxylabs.io parent 7777 0 \
  no-query \
  login=customer-${OXYLABS_USER}-${EXIT_STR}sessid-${SESSID}-sesstime-30:${OXYLABS_PASS}\
  connect-fail-limit=99999999 \
  proxy-only \
  name=oxylabs
cache_peer_access oxylabs allow all
EOF

while true; do squid -f "$SQUID_CONF" -N && break; done