#!/usr/bin/with-contenv bash
#SQUID_CONF=/config/.config/squid.conf
SQUID_CONF=/etc/squid/oxylabs.conf


EXIT_STR=""
[[ -z "$OXYLABS_EXIT" ]] || EXIT_STR="st-${OXYLABS_EXIT}-"

SESSID=$(pwgen 10 1)

while true; do

cat >${SQUID_CONF} <<EOF
http_port 4000
pid_filename /tmp/squid.pid
cache_peer pr.oxylabs.io parent 7777 0 \
  no-query \
  login=customer-${OXYLABS_USER}-${EXIT_STR}sessid-${SESSID}-sesstime-30:${OXYLABS_PASS}\
  connect-fail-limit=99999999 \
  no-query \
  name=oxylabs \
  default
never_direct allow all
cache_peer_access oxylabs allow all
http_access allow localhost
EOF

squid -f "$SQUID_CONF" -N && break

done