#!/usr/bin/with-contenv bash

# Install Telegram PPA
add-apt-repository ppa:atareao/telegram

# Install Signal Repo key
cd /tmp
wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
cat signal-desktop-keyring.gpg | tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

# Add Signal repo
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' |\
  tee /etc/apt/sources.list.d/signal-xenial.list

# Download Google Chrome .deb
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# Add Cloudflare Warp repo
curl https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/cloudflare-client.list

# Update and install packages
apt update
apt install -y telegram signal-desktop cloudflare-warp
apt install -y ./google-chrome-stable_current_amd64.deb

cat > /etc/bash.bashrc<< \EOF

if [ "$(id -u)" -ge 1000 ]; then
export HTTPS_PROXY=http://127.0.0.1:40000
fi
EOF